### ISSUE TITLE
请问...

### ISSUE THREAD

**Issue by EgbertMeow** [cubhe/precise-point-spread-function-estimation#1]
作者您好，能否请您告知运行代码的步骤，我在运行时遇到了许多问题（泪目......）
![image](https://user-images.githubusercontent.com/98024587/163537378-76dbcaac-2dc3-499e-85ec-15e7782c6a6d.png)
![image](https://user-images.githubusercontent.com/98024587/163536844-e5877298-24e7-4fb4-866b-84ec55cf8221.png)
![image](https://user-images.githubusercontent.com/98024587/163536980-6a507753-65c7-4233-bf17-abd4bd122a02.png)
如果能收到您的回复，我将不胜感激！

**Comment by cubhe** [comment]
可以 你加我微信吧 cub_he

**Comment by cubhe** [comment]
fixed by ‘python setup.py install’
